### ISSUE TITLE
3-node minimal cluster without nested virtualisation?

### ISSUE THREAD

**Issue by victorhooi** [cgruver/okd4-upi-lab-setup#12]
There's a lot of people with home-labs, who have setup 3-node (or 4-node) Proxmox HA clusters, to play around with these concepts at home. If you do it on 3 (or 4) physical nodes, performance can also be really good and HA works great.

I'm trying to do the same in OKD/OpenShift, (with Kubevirt and hopefully Ceph/Rook) and your guide looks like the best starting point.

However, I'm still a bit confused about the minimum number of nodes needed, assuming you go with physical nodes. OpenShift docs seems to suggest you need 3 x master nodes, and 2 x worker nodes (as well as a bastion and bootstrap node).

And assuming you want to run Kubevirt on these and Ceph, I'd like to avoid nested virtualisation if possible.

Is there any way of:

- Sharing master/worker duties on the same nodes, without nested virtualisation?
- Running with 1 x master (instead of 3), and 2 x workers?

**Comment by cgruver** [comment]
Yes, If you are doing a UPI (User Provisioned Infrastructure) like I am showing here, then you can go with a minimum of 3 nodes for full HA.  

When you create an install-config.yaml with `worker` replicas set to 0, then the master nodes are automatically marked as schedule-able.  So they will be both master and worker nodes.

That should work for KubeVirt.  You can also set up nested virtualization if you don't want true bare-metal.  I'm getting ready to start using KubeVirt in my lab with nested virtualization.  I'll write up my journey when I get it running.

You can also set up a single node that is both master and worker: https://github.com/cgruver/okd4-single-node-cluster

**Comment by cgruver** [comment]
One other note on a single-node-cluster, you can later add worker nodes to it.  So, you are not stuck with just a single node.  The only caveat is that you can't upgrade it.  Since there's no quorum for etcd, it cannot upgrade itself.  You need three masters for that.

**Comment by victorhooi** [comment]
Got it, ok I will try to give the 3-node setup (or 4-node in my case) a try.

In my case, I'd also like to run Ceph across it, to provide storage for the Kubevirt VMs. Willl you be trying that as well?

Do you know how well https://github.com/cgruver/okd4-upi-lab-setup/blob/master/docs/pages/Ceph.md will work with a 3-node cluster?

You mention at the top you need sufficient RAM - that should be OK in my case.

And secondly this:

> Note: If you do not have worker nodes, then you will need to modify the cluster.yml file to use your master nodes.
> Note: As before, if you do not have dedicated worker nodes, then replace worker with master below.

```
for i in 0 1 2
do
  oc label nodes okd4-worker-${i}.${LAB_DOMAIN} role=storage-node
done
```

That's fine, I can do that, I guess.

But are there any other caveats once I start running Ceph?

I do have separate disks I can pass through to Ceph - do you know how you pass them through to Ceph?

**Comment by cgruver** [comment]
Take a look at: https://github.com/cgruver/okd4-upi-lab-setup/blob/master/Ceph/cluster.yml

This section:

```
storage:
    useAllNodes: false
    useAllDevices: false
    config:
    nodes:
    - name: "okd4-worker-0.%%LAB_DOMAIN%%"
      devices:
      - name: "sdb"
        config:
          osdsPerDevice: "1"
    - name: "okd4-worker-1.%%LAB_DOMAIN%%"
      devices:
      - name: "sdb"
        config:
          osdsPerDevice: "1"
    - name: "okd4-worker-2.%%LAB_DOMAIN%%"
      devices:
      - name: "sdb"
        config:
          osdsPerDevice: "1"
```

Defines the device on each host that will be providing storage to be used by Ceph.  In my case, it's `/dev/sdb` on each of my three worker nodes.  The %%LAB_DOMAIN%% is there for `sed` string replacement to customize it for your domain.

So, in your case you will modify this file with the hostname of each node that will provide storage and the device that will be used.  Note that the device must be an empty block device, no filesystem configured.
