### ISSUE TITLE
Ceph

### ISSUE THREAD

**Issue by disposab1e** [cgruver/okd4-upi-lab-setup#5]
Works like a charme!

i did the last step and applied pvc to registry with patch... but... hm... not shure it is really bound.

**Comment by disposab1e** [comment]
No it's not bound. It's still the emptyDir from previous step.

**Comment by disposab1e** [comment]
tried with a demo pod and new 1GB volume is bound. So it works.... now have to figure out why not with the patch in registry.

**Comment by disposab1e** [comment]
It was added additionally to the emptyDir.

**Comment by disposab1e** [comment]
Also a good exampl [here](https://medium.com/swlh/use-rook-ceph-and-openshift-to-create-dynamic-provisioned-storageclasses-139c50044b5)... works...

Take care: S

Storageclass "myfs" from example must be... all the rest is fine and works with your example tohether. 

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-cephfs
provisioner: rook-ceph.cephfs.csi.ceph.com
parameters:
    clusterID: rook-ceph  
    fsName: myfs  
    pool: myfs-data0
    csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
    csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
    csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
    csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
    csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
    csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
    rook-cephreclaimPolicy: Delete
allowVolumeExpansion: true
reclaimPolicy: Delete
```

**Comment by disposab1e** [comment]
Do you think it makes sense to use disk drives from the master as additional space?

**Comment by cgruver** [comment]
You need to remove the 'emptyDir' from the registry config.

I'll clarify that in the documentation.  The same thing bit me early on.

I didn't use volumes from the masters, mainly to keep them small and dedicated.

**Comment by disposab1e** [comment]
Yes... after removing all is fine! Added my insecure quay registry, now adding openshift auth provider to ldap or perhapskeycloak... and than the heavy lifting with the lab is done. Btw... provisioning with terraform is perfect... you must have a look... I love "terraform destroy" and everything is away in seconds....

**Comment by disposab1e** [comment]
So far.... this works....

Server
-------

`lab.okd.example.com`
```
- cockpit
- libvirt/kvm
- terraform
- packer.io
```

Terraform provisioned Hosts
----------------------------

`bastion.okd.example.com` 
Iinitial kickstart with packer.io and ansible, provsioned with terraform, all service preconfigured and ready to use.

```
- bind
- dhcp
- tftp
- ldap
- nginx
	- centos (mirror)
	- fcos (mirror)
	- ipxe
	- kickstart
	- ignition
- docker (all services with docker-compose)
	- gitlab (auth: ldap)
	- keycloak
	- quay  (auth: ldap)
		- postgres
		- redis
	- artifactory  (auth: ldap)
	- portainer
- openshift-install (ignition files generated and deployey to nginx)
```

`lb.okd.example.com`
ipxe, kickstart and ansible
`- haproxy
`

Rest of the party...

```
bootstrap.okd.example.com (ipxe, ignition)
master-(0-2).okd.example.com (ipxe, ignition)
worker-(0-2).okd.example.com (ipxe, ignition)
```
Ceph on 3 workers, Internal registry using Ceph block, Quay insecure registry integrated.

**Comment by disposab1e** [comment]
You:

```
compute:
- name: worker
  replicas: 3

```

in [docs](https://docs.openshift.com/container-platform/4.4/installing/installing_bare_metal/installing-bare-metal.html#installation-bare-metal-config-yaml_installing-bare-metal).....

You must set the value of the replicas parameter to 0. This parameter controls the number of workers that the cluster creates and manages for you, which are functions that the cluster does not perform when you use user-provisioned infrastructure. You must manually deploy worker machines for the cluster to use before you finish installing OpenShift Container Platform.

**Comment by cgruver** [comment]
Yes, that value of 3 is not really used for anything.  That's left from  some work I was doing with IPI baremetal installs.

The install-config file that I provide is correct:

```
compute:
- name: worker
  replicas: 0
controlPlane:
  name: master
  replicas: 3
```
